name: Build Docker Images

on:
  push:
    branches:
      - osdi-artifact

jobs:
  quick-start:
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@v2

      - name: build docker
        shell: bash
        run: make slice-demo-container

  build-all:
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@v2

      - name: build all except for the riscv toolchain
        shell: bash
        run: |
          make setup
          make all

  quick-build-option1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@v2

      - name: build sliceloader with prebuilt guest linux + qemu + riscv toolchain
        shell: bash
        run: |
          make setup
          make quick-build

