name: Build Docker Images

on:
  push:
    branches:
      - master

jobs:
  dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: checkout sources
        uses: actions/checkout@v2

      - name: checkout submodules
        shell: bash
        run: |
          git -c url."https://${{ secrets.TOKEN }}@github.com".insteadOf="https://github.com" submodule update --init
          git -c url."https://${{ secrets.TOKEN }}@github.com".insteadOf="https://github.com" submodule update --init --recursive slice-boot

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ziqiao
          password: 2a898dad-76a4-4013-bf85-538e94573d27

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.TOKEN}}
          tags: ziqiao/slice-docker:slice
