name: Build Docker Images

on:
  push:
    branches:
      - pub-repo

jobs:
  quick-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@v2

      - name: quick build
        shell: bash
        run: |
          make setup
          make all

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@v2

      - name: quick build
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends \
            make perl python3 gcc libc-dev pkgconf libglib2.0-dev \
            zlib1g-dev build-essential libpixman-1-dev \
            git patch bash device-tree-compiler bison flex \
            gawk expat telnet \
            libyaml-dev libelf-dev gdisk parted \
            libssl-dev bc sudo ninja-build \
            autoconf automake autotools-dev curl python3 \
            libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex \
            gperf libtool patchutils bc zlib1g-dev libexpat-dev \
            libglib2.0-dev libfdt-dev libpixman-1-dev \
            libpng-dev libslirp-dev libpulse-dev
          make setup
          USE_DOCKER=false make slice-ubuntu
          USE_DOCKER=false make install
          USE_DOCKER=false make qemu
          USE_DOCKER=false make linux-riscv-build
          USE_DOCKER=false make linux-riscv-build2
          USE_DOCKER=false make payload-build
          USE_DOCKER=false make run
