name: Build Docker Images

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: checkout sources
        uses: actions/checkout@v2.3.4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ziqiao
          password: 2a898dad-76a4-4013-bf85-538e94573d27

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ziqiao/slice-docker:slice
